mkdir va-zikv-s-genotype/va-zikv-s-genotype.25
/home/dickinsoneb/vadr_files/infernal/binaries/esl-reformat fasta va-zikv-s-genotype/va-zikv-s-genotype.vadr.in.fa.25 > va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.in.fa
/home/dickinsoneb/vadr_files/infernal/binaries/esl-seqstat --dna -a va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.in.fa > va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.seqstat
/home/dickinsoneb/vadr_files/ncbi-blast/bin/blastn -num_threads 1 -query va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.blastn.fa -db zikv-genotype-models2/zikv.fa -out va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.rpn.cls.blastn.out -word_size 7 -reward 1 -penalty -2 -xdrop_gap_final 110 -gapopen 2 -gapextend 1
/home/dickinsoneb/vadr_files/vadr/parse_blast.pl --program n --input va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.rpn.cls.blastn.out --splus > va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.rpn.cls.blastn.summary.txt
grep -v ^# va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.rpn.cls.tblout | sed 's/  */ /g' | sort -k 1,1 -k 3,3rn > va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.rpn.cls.tblout.sort
cat va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.rpn.cdt.KU509998.tblout | grep -v ^# | sed 's/  */ /g' | sort -k 1,1 -k 15,15rn -k 16,16g > va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.rpn.cdt.tblout.sort
/home/dickinsoneb/vadr_files/ncbi-blast/bin/blastn -num_threads 1 -query va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.blastn.rpn.fa -db zikv-genotype-models2/zikv.fa -out va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.std.cls.blastn.out -word_size 7 -reward 1 -penalty -2 -xdrop_gap_final 110 -gapopen 2 -gapextend 1
/home/dickinsoneb/vadr_files/vadr/parse_blast.pl --program n --input va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.std.cls.blastn.out --splus > va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.std.cls.blastn.summary.txt
grep -v ^# va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.std.cls.tblout | sed 's/  */ /g' | sort -k 1,1 -k 3,3rn > va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.std.cls.tblout.sort
cat va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.std.cdt.KU509998.tblout | grep -v ^# | sed 's/  */ /g' | sort -k 1,1 -k 15,15rn -k 16,16g > va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.std.cdt.tblout.sort
/home/dickinsoneb/vadr_files/infernal/binaries/cmfetch zikv-genotype-models2/zikv.cm KU509998 | /home/dickinsoneb/vadr_files/infernal/binaries/cmalign  --dnaout --verbose --cpu 1 --ifile va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.KU509998.align.r1.s0.ifile -o va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.KU509998.align.r1.s0.stk --tau 0.001 --mxsize 4000.00 --sub --notrunc -g --fixedtau --flanktoins 0.1 --flankselfins 0.8 - va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.KU509998.a.subseq.fa > va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.KU509998.align.r1.s0.stdout 2>&1
cat va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.KU509998.align.r1.s0.stdout > va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.KU509998.align.stdout
cat va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.KU509998.align.r1.s0.ifile > va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.KU509998.align.ifile
/home/dickinsoneb/vadr_files/infernal/binaries/cmfetch zikv-genotype-models2/zikv.cm KU509998 | /home/dickinsoneb/vadr_files/infernal/binaries/cmemit -c - > va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.KU509998.cseq.fa
/home/dickinsoneb/vadr_files/infernal/binaries/esl-alimerge --list --outformat stockholm --dna va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.KU509998.align.stk.list > va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.KU509998.rfrna.align.rpstk
/home/dickinsoneb/vadr_files/infernal/binaries/esl-reformat --informat stockholm -d pfam va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.KU509998.align.rpstk > va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.KU509998.align.rpstk.stockholm.pfam
/home/dickinsoneb/vadr_files/infernal/binaries/esl-alimanip --informat stockholm --dna --outformat stockholm --num-rf va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.KU509998.align.rpstk.stockholm.new.pfam > va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.KU509998.align.stk
/home/dickinsoneb/vadr_files/infernal/binaries/esl-alimerge --list --outformat afa --dna va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.KU509998.align.stk.list > va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.KU509998.align.rpafa
/home/dickinsoneb/vadr_files/infernal/binaries/esl-reformat --informat afa -d pfam va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.KU509998.align.rpafa > va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.KU509998.align.rpafa.afa.pfam
/home/dickinsoneb/vadr_files/infernal/binaries/esl-alimanip --informat stockholm --dna --outformat afa va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.KU509998.align.rpafa.afa.new.pfam > va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.KU509998.align.afa
cat va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.KU509998.CDS.1.pv.fa >> va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.KU509998.pv.blastx.fa
/home/dickinsoneb/vadr_files/ncbi-blast/bin/blastx -num_threads 1 -num_alignments 20 -query va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.KU509998.pv.blastx.fa -db zikv-genotype-models2/KU509998.vadr.protein.fa -seg no -out va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.KU509998.blastx.out
/home/dickinsoneb/vadr_files/vadr/parse_blast.pl --program x --input va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.KU509998.blastx.out > va-zikv-s-genotype/va-zikv-s-genotype.25/va-zikv-s-genotype.25.vadr.KU509998.blastx.summary.txt
# Tue Mar 18 12:01:28 EDT 2025
# Linux sge1643 4.18.0-553.40.1.el8_10.x86_64 #1 SMP Mon Feb 10 12:11:18 EST 2025 x86_64 x86_64 x86_64 GNU/Linux
[ok]
